### ISSUE TITLE
ElasticExplore not finding spaceid that exists

### ISSUE THREAD

**Issue by alfinhaji** [qlik-oss/gopherciser#157]
### Description

So looks like elasticexplore by spaceid isnt working.   I suspect during elasticopenhub when we make the call to /api/v1/spaces?limit=100 we are storing the spaceid, but when we attempt to find it in the artifact it cant be found

https://github.com/qlik-oss/gopherciser/blob/master/session/artifactmap.go#L318

Example of scenario attached

### Steps to Reproduce

1. See attached scenario file, which runs against perf6.eu.qlik-stage.com.  Run this scenario with traffic logs enabled and notice even though the space exists (response in previous /api/v1/spaces call during elasticopenhub, we still get space id not found.
[qcsTest.txt](https://github.com/qlik-oss/gopherciser/files/5660884/qcsTest.txt)

##### Expected behavior

Space id should be found as it exists

##### Actual behavior

Space id not found

##### Operating system
```
QCS perf6.eu.qlik-stage.com tenant



```

### Versions

* Version of Go (go version): 
* [Other relevant versions]

**Comment by DnlLrssn** [comment]
setting `"keepcurrent": true` will temporary fix the issue, this will however also keep any "personal" apps etc in list. It manifests as we now clear the entire map of everything. Will make a modification which keeps spaces.
